config/routes.rb
Rails.application.routes.draw do
root 'welcome#index'

  resources :users
  resources :sessions, only:[:new, :create, :destroy]
  resources :posts

  get 'registrations/new', to: 'registrations#new'
  post '/users', to: 'registrations#create'

  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts

  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :email, presence: true,
            uniqueness: true,
            format: {with: /\A[\w+\-.]+@[a-z\d\-]+\.[a-z]+\z/i, message: " is invalid"}

  validates :password, length: {minimum: 8}, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def logged_in?
    session[:id].present? && User.find(session[:id])
  end

  def post_belongs_to_user?(post)
    user = User.find(session[:id])
    post.user_id == user.id
  end

  helper_method :logged_in?, :post_belongs_to_user?
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    @post = Post.new(post_params)
    user = User.find(session[:id])
    @post.user_id = user.id

    if @post.save
      redirect_to user_path(user)
    else
      flash.now[:notice]
      render user_path(user)
    end
  end

  def new
    @post = Post.new
  end

  def show
    @posts = Post.all
  end

  def destroy
    user = User.find(session[:id])
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to user_path(user)
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:notice] = 'invalid username / password'
      render 'users/index'
    end
  end

  def destroy
    session[:id] = nil
    flash[:notice] = 'You are logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.create(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render 'registrations/new'
    end
  end

  def show
    @posts = Post.all
    @user = User.find(params[:id])
    session[:id] = @user.id
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form.html.erb
<div class="form">
  <h3>Post Message</h3>
  <%= form_for @post do |f| %>

    <% if @post.errors.present? %>
      <div class="errors">
        <h1>There was an error</h1>
        <ul class="error-list">
          <% @diva.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= f.text_area :body, :size => "25x5" %>
    </p>

    <p>
      <%= f.submit "Submit Post", class: "submit-post" %>
    </p>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReviewApp</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="wrapper">
    <h1>My Practive / Review App</h1>
  </div>
</header>
<div class="notice">
  <%= flash[:notice] %>
</div>

<div class="links">
  <% if logged_in? %>
    <li><%= link_to "Logout", logout_path, method: :delete %></li>
    <% if params[:action] != "new" %>
      <li><%= link_to "Write A Post", new_post_path %></li>
    <% end %>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div class="home">
  <%= form_for :session, url: sessions_path do |f| %>

    <p>
      <%= f.label :email, class: "form-label" %>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.label :password, class: "form-label" %>
      <%= f.password_field :password %>
    </p>

    <p>
      <%= f.submit "Login", class: "submit-button" %>
    </p>

  <% end %>
</div>

app/views/users/show.html.erb
<div class="greeting">
  <h1>Welcome, <%= @user.first_name %>!</h1>
</div>

<div class="posts">
  <h2>My Posts</h2>
  <% @posts.each do |post| %>
    <% if post_belongs_to_user?(post) %>
      <p>
        <%= post.body %>
      <%= link_to "Delete Post", post_path(post), method: :delete, class: "delete" %>
      </p>
    <% end %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="home">
<h3><%= link_to "Create An Account", registrations_new_path %></h3>
<h3><%= link_to "Login", users_path %></h3>
</div>